//package com.baoju.weixin.entity;
//
//// Generated 2015-9-22 9:29:15 by Hibernate Tools 4.0.0
//
//import java.util.Date;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.GeneratedValue;
//import static javax.persistence.GenerationType.IDENTITY;
//import javax.persistence.Id;
//import javax.persistence.Table;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;
//
///**
// * SysDeviceLightBind generated by hbm2java
// */
//@Entity
//@Table(name = "sys_device_light_bind", catalog = "smartlight_dev")
//public class SysDeviceLightBind implements java.io.Serializable {
//
//	private Long id;
//	private Long DId;
//	private Long createBy;
//	private String lightId;
//	private String openid;
//	private Date createTime;
//	private String name;
//	private Integer bitNum;
//	private Integer lightType;
//	private String fogDid;
//
//	public SysDeviceLightBind() {
//	}
//
//	public SysDeviceLightBind(Date createTime) {
//		this.createTime = createTime;
//	}
//
//	public SysDeviceLightBind(Long DId, Long createBy, String lightId,
//			String openid, Date createTime, String name, Integer bitNum,
//			Integer lightType,String fogDid) {
//		this.DId = DId;
//		this.createBy = createBy;
//		this.lightId = lightId;
//		this.openid = openid;
//		this.createTime = createTime;
//		this.name = name;
//		this.bitNum = bitNum;
//		this.lightType = lightType;
//		this.fogDid = fogDid;
//	}
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//	@Column(name = "id", unique = true, nullable = false)
//	public Long getId() {
//		return this.id;
//	}
//
//	public void setId(Long id) {
//		this.id = id;
//	}
//
//	@Column(name = "d_id")
//	public Long getDId() {
//		return this.DId;
//	}
//
//	public void setDId(Long DId) {
//		this.DId = DId;
//	}
//
//	@Column(name = "create_by")
//	public Long getCreateBy() {
//		return this.createBy;
//	}
//
//	public void setCreateBy(Long createBy) {
//		this.createBy = createBy;
//	}
//
//	@Column(name = "light_id")
//	public String getLightId() {
//		return this.lightId;
//	}
//
//	public void setLightId(String lightId) {
//		this.lightId = lightId;
//	}
//
//	@Column(name = "openid", length = 100)
//	public String getOpenid() {
//		return this.openid;
//	}
//
//	public void setOpenid(String openid) {
//		this.openid = openid;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "create_time", nullable = false, length = 19)
//	public Date getCreateTime() {
//		return this.createTime;
//	}
//
//	public void setCreateTime(Date createTime) {
//		this.createTime = createTime;
//	}
//
//	@Column(name = "name", length = 100)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "bit_num")
//	public Integer getBitNum() {
//		return this.bitNum;
//	}
//
//	public void setBitNum(Integer bitNum) {
//		this.bitNum = bitNum;
//	}
//
//	@Column(name = "light_type")
//	public Integer getLightType() {
//		return this.lightType;
//	}
//
//	public void setLightType(Integer lightType) {
//		this.lightType = lightType;
//	}
//	
//	@Column(name = "fog_did")
//	public String getFogDid() {
//		return fogDid;
//	}
//
//	public void setFogDid(String fogDid) {
//		this.fogDid = fogDid;
//	}
//
//}
