package com.baoju.weixin.entity;

// Generated 2015-9-22 9:29:15 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysDeviceUser generated by hbm2java
 */
@Entity
@Table(name = "sys_device_user", catalog = "smartlight_dev")
public class SysDeviceUser implements java.io.Serializable {

	private String openid;
	private String uid;
	private String token;
	private Long expireAt;

	public SysDeviceUser() {
	}

	public SysDeviceUser(String openid) {
		this.openid = openid;
	}

	public SysDeviceUser(String openid, String uid, String token, Long expireAt) {
		this.openid = openid;
		this.uid = uid;
		this.token = token;
		this.expireAt = expireAt;
	}

	@Id
	@Column(name = "openid", unique = true, nullable = false, length = 200)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "uid", length = 200)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "token", length = 200)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "expire_at")
	public Long getExpireAt() {
		return this.expireAt;
	}

	public void setExpireAt(Long expireAt) {
		this.expireAt = expireAt;
	}

}
