package com.baoju.weixin.entity;

// Generated 2015-9-22 9:29:15 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysLog generated by hbm2java
 */
@Entity
@Table(name = "sys_log", catalog = "smartlight_dev")
public class SysLog implements java.io.Serializable {

	private Long id;
	private Date createTime;
	private String logContent;
	private String openid;
	private Integer operRes;
	private Long userId;
	private Integer isPush;
	private String ipAddr;
	private String operType;
	private Long DId;

	public SysLog() {
	}

	public SysLog(Date createTime) {
		this.createTime = createTime;
	}

	public SysLog(Date createTime, String logContent, String openid,
			Integer operRes, Long userId, Integer isPush, String ipAddr,
			String operType, Long DId) {
		this.createTime = createTime;
		this.logContent = logContent;
		this.openid = openid;
		this.operRes = operRes;
		this.userId = userId;
		this.isPush = isPush;
		this.ipAddr = ipAddr;
		this.operType = operType;
		this.DId = DId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "log_content", length = 65535)
	public String getLogContent() {
		return this.logContent;
	}

	public void setLogContent(String logContent) {
		this.logContent = logContent;
	}

	@Column(name = "openid", length = 500)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "oper_res")
	public Integer getOperRes() {
		return this.operRes;
	}

	public void setOperRes(Integer operRes) {
		this.operRes = operRes;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "is_push")
	public Integer getIsPush() {
		return this.isPush;
	}

	public void setIsPush(Integer isPush) {
		this.isPush = isPush;
	}

	@Column(name = "ip_addr", length = 50)
	public String getIpAddr() {
		return this.ipAddr;
	}

	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	@Column(name = "oper_type", length = 100)
	public String getOperType() {
		return this.operType;
	}

	public void setOperType(String operType) {
		this.operType = operType;
	}

	@Column(name = "d_id")
	public Long getDId() {
		return this.DId;
	}

	public void setDId(Long DId) {
		this.DId = DId;
	}

}
