package com.baoju.weixin.entity;

// Generated 2015-9-22 9:29:15 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.baoju.common.util.str.StringUtils;


/**
 * SysScene generated by hbm2java
 */
@Entity
@Table(name = "sys_scene", catalog = "smartlight_dev")
public class SysScene implements java.io.Serializable {

	private Long id;//情景主键
	private String name;//情景名称
	private Long did;//设备Id
	private Integer sceneType;//情景类型，0-单灯，1-多灯
	private String openid;//用户Id
	private Long createBy;//创建人
	private String createTime;//创建时间
	private String lightId;
	private String fogDid;

	public SysScene() {
	}


	public SysScene(String name, Long did, Integer sceneType, String openid,
			Long createBy) {
		this.name = name;
		this.did = did;
		this.sceneType = sceneType;
		this.openid = openid;
		this.createBy = createBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "did")
	public Long getDid() {
		return this.did;
	}

	public void setDid(Long did) {
		this.did = did;
	}

	@Column(name = "scene_type")
	public Integer getSceneType() {
		return this.sceneType;
	}

	public void setSceneType(Integer sceneType) {
		this.sceneType = sceneType;
	}

	@Column(name = "openid", length = 100)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	
	@Column(columnDefinition="timestamp",name = "create_time", nullable = false, length = 19,insertable=false,updatable=false)
	public String getCreateTime() {
		return StringUtils.formatTimestamp(this.createTime);
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "light_id")
	public String getLightId() {
		return lightId;
	}

	public void setLightId(String lightId) {
		this.lightId = lightId;
	}

	@Column(name = "fog_did", length = 100)
	public String getFogDid() {
		return fogDid;
	}


	public void setFogDid(String fogDid) {
		this.fogDid = fogDid;
	}
	

}
