package com.baoju.weixin.entity;

// Generated 2015-9-23 9:42:35 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysSceneDetail generated by hbm2java
 */
@Entity
@Table(name = "sys_scene_detail", catalog = "smartlight_dev")
public class SysSceneDetail implements java.io.Serializable {

	private Long id; //情景明细Id
	private Long sceneId;//所属情景Id
	private String lightId;//灯Id
	private Long createBy;//创建人
	private String createTime;//创建时间
	private Long brightness;//亮度
	private Long temperature;//色温
	private Long rgb;//rgb
	private Integer onOff;//开关？0代表关？
	private Integer swithLight;//光源切换值
	private Integer colorBrightness;//彩灯亮度
	private Integer rgbshade;

	public SysSceneDetail() {
	}


	public SysSceneDetail(Long sceneId, String lightId, Long createBy,
			Long brightness, Long temperature, Long rgb,
			Integer onOff, Integer swithLight,
			Integer colorBrightness) {
		this.sceneId = sceneId;
		this.lightId = lightId;
		this.createBy = createBy;
		this.brightness = brightness;
		this.temperature = temperature;
		this.rgb = rgb;
		this.onOff = onOff;
		this.swithLight = swithLight;
		this.colorBrightness = colorBrightness;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "scene_id")
	public Long getSceneId() {
		return this.sceneId;
	}

	public void setSceneId(Long sceneId) {
		this.sceneId = sceneId;
	}

	@Column(name = "light_id")
	public String getLightId() {
		return this.lightId;
	}


	public void setLightId(String lightId) {
		this.lightId = lightId;
	}

	@Column(name = "create_by")
	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	@Column(columnDefinition="timestamp",name = "create_time", nullable = false, length = 19,insertable=false,updatable=false)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "brightness")
	public Long getBrightness() {
		return this.brightness;
	}

	public void setBrightness(Long brightness) {
		this.brightness = brightness;
	}

	@Column(name = "temperature")
	public Long getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Long temperature) {
		this.temperature = temperature;
	}

	@Column(name = "rgb")
	public Long getRgb() {
		return this.rgb;
	}

	public void setRgb(Long rgb) {
		this.rgb = rgb;
	}

	@Column(name = "on_off")
	public Integer getOnOff() {
		return this.onOff;
	}

	public void setOnOff(Integer onOff) {
		this.onOff = onOff;
	}

	@Column(name = "swith_light")
	public Integer getSwithLight() {
		return this.swithLight;
	}

	public void setSwithLight(Integer swithLight) {
		this.swithLight = swithLight;
	}

	@Column(name = "color_brightness")
	public Integer getColorBrightness() {
		return this.colorBrightness;
	}

	public void setColorBrightness(Integer colorBrightness) {
		this.colorBrightness = colorBrightness;
	}

	@Column(name = "rgbshade")
	public Integer getRgbshade() {
		return rgbshade;
	}

	public void setRgbshade(Integer rgbshade) {
		this.rgbshade = rgbshade;
	}
	
}
