package com.baoju.weixin.entity;

// Generated 2015-9-22 9:29:15 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysTimetask generated by hbm2java
 */
@Entity
@Table(name = "sys_timetask", catalog = "smartlight_dev")
public class SysTimetask implements java.io.Serializable {

	private Long id;
	private String openid;
	private String lightId;
	private String createBy;
	private Date createTime;
	private Integer brightness;
	private Integer temperature;
	private Integer rgb;
	private Integer onOff;
	private Date runTime;
	private Integer colorBrightness;
	private Integer swithLight;

	public SysTimetask() {
	}

	public SysTimetask(Date createTime) {
		this.createTime = createTime;
	}

	public SysTimetask(String openid, String lightId, String createBy,
			Date createTime, Integer brightness, Integer temperature, Integer rgb,
			Integer onOff) {
		this.openid = openid;
		this.lightId = lightId;
		this.createBy = createBy;
		this.createTime = createTime;
		this.brightness = brightness;
		this.temperature = temperature;
		this.rgb = rgb;
		this.onOff = onOff;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "openid", length = 100)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "light_id")
	public String getLightId() {
		return this.lightId;
	}

	public void setLightId(String lightId) {
		this.lightId = lightId;
	}

	@Column(name = "create_by")
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "brightness")
	public Integer getBrightness() {
		return this.brightness;
	}

	public void setBrightness(Integer brightness) {
		this.brightness = brightness;
	}

	@Column(name = "temperature")
	public Integer getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Integer temperature) {
		this.temperature = temperature;
	}

	@Column(name = "rgb")
	public Integer getRgb() {
		return this.rgb;
	}

	public void setRgb(Integer rgb) {
		this.rgb = rgb;
	}

	@Column(name = "on_off")
	public Integer getOnOff() {
		return this.onOff;
	}

	public void setOnOff(Integer onOff) {
		this.onOff = onOff;
	}

	@Column(name = "run_time")
	public Date getRunTime() {
		return runTime;
	}

	public void setRunTime(Date runTime) {
		this.runTime = runTime;
	}

	@Column(name = "color_brightness")
	public Integer getColorBrightness() {
		return colorBrightness;
	}

	public void setColorBrightness(Integer colorBrightness) {
		this.colorBrightness = colorBrightness;
	}

	@Column(name = "swith_light")
	public Integer getSwithLight() {
		return swithLight;
	}

	public void setSwithLight(Integer swithLight) {
		this.swithLight = swithLight;
	}
	
	
	
}
